version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kizie_db
      POSTGRES_USER: kizie_user
      POSTGRES_PASSWORD: kizie_password
    volumes:
      - kizie_db_data:/var/lib/postgresql/data

volumes:
  kizie_db_data:
